### ISSUE TITLE
Support dump of the conntrack table 

### ISSUE THREAD

**Issue by guvenc** [ironcore-dev/dpservice#418]
We need to enhance `dpservice-cli` and grpc interface to be able to support dumping of the conntrack table contents. (flows)
smt like this:
`dpservice-cli list flows --id=vm2`
`dpservice-cli get flow flow_id`

The id can be the five tuple hash that we internally use. Also the 5 Tuple of the flow and some internal states should be printed.
(e.g whether it is offloaded, whether it is LB, NAT etc)

These are the first thoughts from my side. We can discuss this further.
@byteocean  @PlagueCZ

**Comment by PlagueCZ** [comment]
Superseded by #498
