### ISSUE TITLE
dpservice telemetry metrics to expose the internal table fullness

### ISSUE THREAD

**Issue by guvenc** [ironcore-dev/dpservice#438]
The most obvious and the important one is the fullness of the conntrack table but other tables which are used in dpservice can also have such metrics. Some suggestions would be:

- LB/DNAT Table fullness. 
- How many (vf) interfaces are actively used on that dp-service. (Interface table fullness)

CC: @PlagueCZ @dnlvanco

**Comment by PlagueCZ** [comment]
I have separated the firewall output into another issue for clarity.

I have applied all suggestions except for `"loadbalancer_map_table"` which is now `"loadbalancer_id_table"` to better reflect the fact that it simply maps IDs to loadbalancer data.

This is the new proposal (virtual service included for completeness, they are of course still conditionally compiled):
```
$ echo "/dp_service/table/saturation" | dpdk-telemetry.py |jq
{
  "/dp_service/table/saturation": {
    "virtsvc_table_0": {
      "capacity": 64512,
      "entries": 0
    },
    "virtsvc_table_1": {
      "capacity": 64512,
      "entries": 0
    },
    "conntrack_table": {
      "capacity": 850000,
      "entries": 6
    },
    "interface_table": {
      "capacity": 128,
      "entries": 2
    },
    "snat_table": {
      "capacity": 4032,
      "entries": 0
    },
    "dnat_table": {
      "capacity": 4032,
      "entries": 0
    },
    "nat_portmap_table": {
      "capacity": 850000,
      "entries": 0
    },
    "nat_portoverload_table": {
      "capacity": 850000,
      "entries": 0
    },
    "loadbalancer_table": {
      "capacity": 256,
      "entries": 0
    },
    "loadbalancer_map_table": {
      "capacity": 256,
      "entries": 0
    },
    "vni_table": {
      "capacity": 512,
      "entries": 1
    },
    "vnf_table": {
      "capacity": 1000,
      "entries": 2
    },
    "reverse_vnf_table": {
      "capacity": 1000,
      "entries": 2
    }
  }
}
```
