### ISSUE TITLE
Investigate Mellanox Multiport Eswitch for ECMP in dpservice

### ISSUE THREAD

**Issue by guvenc** [ironcore-dev/dpservice#478]
# Summary

DPDK Mellanox documentation talks about a feature called Multiport Eswitch.
https://doc.dpdk.org/guides/nics/mlx5.html#multiport-e-switch

This feature needs an investigation how this can be used to support ECMP in dpservice.
- Make Multiport Eswitch work.
- Test rte_flow rules to match on VF_PF0 and to forward to PF1. Is this possible without hairpins with the new feature ? 

## Motivation

To support ECMP hardware offloading in dpservice with an easier and less complex way.

**Comment by byteocean** [comment]
## Steps
- [x] Gather know-how
- [x] Environment preparation
- [ ] Test using tool and the programming way
- [ ] Disturbs FRR

**Comment by guvenc** [comment]
Nvidia tells in dpdk mailing list that IPinIP is not supported with rte_flow async/template API which is a prerequisite for multiport eswitch usage.

https://mails.dpdk.org/archives/users/2024-March/007603.html

**Comment by guvenc** [comment]
Remaining part is tracked in issue #593
